=== AngelHerradaP/LLMM/Tema4/DTD/Ejercicio4.3/doctype.dtd
<!ELEMENT restaurante (menu, recetas, clientes)>
    <!ELEMENT menu (plato+)>
        <!ELEMENT plato (nombreM, categoriaM, ingredientesM, precioM)>
            <!ELEMENT nombreM (#PCDATA)>
            <!ELEMENT categoriaM (#PCDATA)>
            <!ELEMENT ingredientesM (ingredienteM+)>
                <!ELEMENT ingredienteM (#PCDATA)>
            <!ELEMENT precioM (#PCDATA)>
    <!ELEMENT recetas (receta+)>
        <!ELEMENT receta (nombreR, ingredientesR, preparacionR)>
            <!ELEMENT nombreR (#PCDATA)>
            <!ELEMENT ingredientesR (ingredienteR+)>
                <!ELEMENT ingredienteR (nombreIngredienteR)>
                    <!ELEMENT nombreIngredienteR (#PCDATA)>
            <!ELEMENT preparacionR (pasoR+)>
                <!ELEMENT pasoR (#PCDATA)>
    <!ELEMENT clientes (cliente+)>
        <!ELEMENT cliente (nombreC, telefonoC, correoC, pedidosC)>
            <!ELEMENT nombreC (#PCDATA)>
            <!ELEMENT telefonoC (#PCDATA)>
            <!ELEMENT correoC (#PCDATA)>
            <!ELEMENT pedidosC (fechaC, platosC)>
                <!ELEMENT fechaC (#PCDATA)>
                <!ELEMENT platosC (platoClientesC+)>
                    <!ELEMENT platoClientesC (#PCDATA)>

<!ATTLIST categoriaM tipo CDATA #IMPLIED>
<!ATTLIST precioM moneda CDATA #REQUIRED>
<!ATTLIST nombreR tipo (adultos | ninyos) #REQUIRED>
<!ATTLIST ingredienteR cantidad CDATA #REQUIRED>

=== AngelHerradaP/LLMM/Tema4/DTD/Ejercicio4.3/especie.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE restaurante SYSTEM "doctype.dtd">
<restaurante>
    <menu>
        <plato>
            <nombreM></nombreM>
            <categoriaM></categoriaM>
            <ingredientesM>
                <ingredienteM></ingredienteM>
            </ingredientesM>
            <precioM moneda=""></precioM>
        </plato>
    </menu>
    <recetas>
        <receta>
            <nombreR tipo="adultos"></nombreR>
            <ingredientesR>
                <ingredienteR cantidad="">
                    <nombreIngredienteR></nombreIngredienteR>
                </ingredienteR>
            </ingredientesR>
            <preparacionR>
                <pasoR></pasoR>
            </preparacionR>
        </receta>   
    </recetas>
    <clientes>
        <cliente>
            <nombreC></nombreC>
            <telefonoC></telefonoC>
            <correoC></correoC>
            <pedidosC>
                <fechaC></fechaC>
                <platosC>
                    <platoClientesC></platoClientesC>
                </platosC>
            </pedidosC>
        </cliente>
    </clientes>
</restaurante>
